language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - cd pymonitoringplugins
  - cd tests
  - python test_ftp.py -h
after_success:
  - coveralls
