language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install python-dev
install:
    - pip install -r requirements.txt
    - pip install coveralls
script: nosetests
after_success:
    - coveralls
sudo: false

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: "Canux"
    password:
    secure:
